### ISSUE TITLE
预训练模型下载

### ISSUE THREAD

**Issue by caochong12** [ltttpku/CMMP#1]
![1](https://github.com/user-attachments/assets/32d8dfbb-6783-4f09-a117-e27d6554a99f)
 作者@ltttpku 您好，
        我对您的工作非常感兴趣，请问：上述图像中的两个预训练模型应该在哪里下载呀，期待您在百忙中的回复，万分感谢！

**Comment by ltttpku** [comment]
Thanks for your interest! You can download the weights from the following links:
```
_MODELS = {
    "ViT-B/16": "https://openaipublic.azureedge.net/clip/models/5806e77cd80f8b59890b7e101eabd078d9fb84e6937f9e85e4ecb61988df416f/ViT-B-16.pt",
    "ViT-L/14@336px": "https://openaipublic.azureedge.net/clip/models/3035c92b350959924f9f00213499208652fc7ea050643e8b385c2dac08641f02/ViT-L-14-336px.pt",
}
```

**Comment by caochong12** [comment]
Thank you very much for your reply！
