### ISSUE TITLE
Harmonic mean

### ISSUE THREAD

**Issue by ChelsieLei** [ltttpku/CMMP#11]
Hi @ltttpku,

Thanks for your nice work! 

I have a question about the harmonic mean. For some classes, the AP is almost 0, and then the HM will be 0 without any processing. Then, I think you processed the results to make the HM result meaningful. May I know how you processed it? 

Thanks!
Chelsie

**Comment by ltttpku** [comment]
Hi, the harmonic mean is computed between the mAP of the seen classes and the mAP of the unseen classes.

**Comment by ChelsieLei** [comment]
Thanks for your reply. It is very helpful!
