### ISSUE TITLE
Global Prior in Default Setting

### ISSUE THREAD

**Issue by kkayla99** [ltttpku/CMMP#12]
Hello, I have a question regarding the global prior in the **default** setting:
```
self.global_prior = pickle.load(open(f'./pairwise_prior/setting={args.zs_type}_method=2_coord=1_k={args.n_gsp}.pkl','rb'))
parser.add_argument('--zs_type', type=str, default='unseen_verb', choices=['rare_first', 'non_rare_first', 'unseen_verb', 'unseen_object', 'uc0', 'uc1', 'uc2', 'uc3', 'uc4'])
```   
Does this imply that when I train the model using the default setting, the `global_prior` will be loaded from the file named `setting=unseen_verb_method=2_coord=1_k=10.pkl`?

**Comment by ltttpku** [comment]
Hi, in this work, we focus on exploring various zero-shot settings. You can extract the global prior from the entire training set and adjust the corresponding parameters accordingly.
