### ISSUE TITLE
How to use inference.py

### ISSUE THREAD

**Issue by markryanwww** [ltttpku/CMMP#3]
Hi,thanks for your excellent work,I'd like to ask you a question.How to use inference.py ,I don't find any script.Looking forward to your reply

**Comment by ltttpku** [comment]
Thank you for your interest in our work. 
To run the inference script, you can execute the following command: 
`python inference.py --index 8789 --pretrained checkpoints/detr-r50-hicodet.pth --use_insadapter --num_classes 117 --use_multi_hot --prompt_learning --LA --eval --resume [CKPT]`.

**Comment by markryanwww** [comment]
I really appreciate it
