### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Maritime-Moon** [ltttpku/CMMP#4]

**Comment by Maritime-Moon** [comment]
I should download that VCOCO dataset. Why does the training set in the dataset I downloaded have 82,783 images, and I see that what you are saying seems to be only 10,346 images?

**Comment by ltttpku** [comment]
The dataset you mentioned is likely MS COCO, while V-COCO is a subset containing 10,346 annotated images. Please refer to [their paper](https://arxiv.org/abs/2007.12407) or the brief introduction [here](https://paperswithcode.com/dataset/v-coco) for more details.
