### ISSUE TITLE
How to training/testing --zs_type {UC}

### ISSUE THREAD

**Issue by markryanwww** [ltttpku/CMMP#7]
Hi, thank you for your great work! I have got some results like "NF/RF/UV/UO/hico_defaults" by your scripts. 
But I currently cannot find the “UC”  in both the scripts and the MODEL ZOO you provided. I noticed that the `--zs_type` is defined as `uc0,uc1,uc2,uc3,uc4` in `main_tip_finetune.py`. I would like to know what that means. Additionally, can the UC training/testing scripts be implemented by simply modifying the `--zs_type`? 
Thank you again for the open-source code, and I look forward to your reply.

**Comment by ltttpku** [comment]
Thanks for you interest in our work! The UC setting reports the average performance of `uc0,uc1,uc2,uc3,uc4`. As a result, you can modify `--zs_type` to replicate the results. If you encounter any issues during replication, please don't hesitate to reach out!

**Comment by hxqstree** [comment]
Hi, thanks for your excellent work!
I want to know what is the meaning of uc0, uc1... and why they are set separately.

**Comment by markryanwww** [comment]
> Hi, thanks for your excellent work! I want to know what is the meaning of uc0, uc1... and why they are set separately.

Hi, do you know why they are set separately now? I still donot know
