### ISSUE TITLE
use of kmeans to obtain global spatial priors

### ISSUE THREAD

**Issue by zkjsi** [ltttpku/CMMP#8]
Nice work!
I am very interested in your work, but I have a question. In your paper, you mentioned the use of kmeans to obtain global spatial priors, but I did not see the relevant part in your code, may I ask where this part is specifically?

**Comment by ltttpku** [comment]
Hi, we don't plan to release this part of the code at the moment. However, you can directly use the provided spatial patterns. Alternatively, you could implement a clustering procedure on your own, which should be fairly straightforward! :)

**Comment by zkjsi** [comment]
Ok,thank you for your reply!

**Comment by hxqstree** [comment]
Hello, thank you for your excellent work! I saw in your supplementary materials that there was a discussion about different values ​​of k, but I couldn't find that part in supplementary materials. Could you please tell me what values ​​of k you set at the time?
