### ISSUE TITLE
About pretrained CLIP weight

### ISSUE THREAD

**Issue by YangJae96** [ltttpku/CMMP#9]
Hi. Thank you for your great work.

How can I download the pretrained CLIP, ViT-B-16.pt?

In OpenAI, CLIP github, they only bring the VIT-B-16 version with the codes.
```
import clip
import torch

model, preprocess = clip.load("ViT-B/16", device="cuda" if torch.cuda.is_available() else "cpu")
```

I cant figure out how to download ViT-B/16.pt weights and save it in the local.

Can I get some help?

**Comment by ltttpku** [comment]
Thanks for your interest in our work.
The CLIP weights can be downloaded from the [URLs here](https://github.com/openai/CLIP/blob/main/clip/clip.py#L30).

**Comment by YangJae96** [comment]
@ltttpku 
Thanks!
